"""
Flood Classifier Training Script

Trains YOLOv8 classifier for flood photo verification.

CRITICAL SAFETY REQUIREMENTS:
- Target: <2% False Negative Rate (cannot miss real floods)
- Uses class weighting to penalize missed floods
- Validates recall before saving best model

Prerequisites:
1. Run download_kaggle_datasets.py to get training data
2. Run scrape_flood_images.py for India-specific images
3. Run preprocess_flood_images.py to prepare dataset

Usage:
    python -m apps.ml-service.scripts.train_flood_classifier
    python -m apps.ml-service.scripts.train_flood_classifier --epochs 50
    python -m apps.ml-service.scripts.train_flood_classifier --resume
"""

import argparse
import json
import logging
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, Tuple
import shutil

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Base paths
SCRIPT_DIR = Path(__file__).parent
ML_SERVICE_DIR = SCRIPT_DIR.parent
DATA_DIR = ML_SERVICE_DIR / "data"
MODELS_DIR = ML_SERVICE_DIR / "models"
FLOOD_IMAGES_DIR = DATA_DIR / "flood_images"

# Training defaults
DEFAULT_EPOCHS = 100
DEFAULT_BATCH = 16
DEFAULT_IMGSZ = 640


def check_dataset() -> Tuple[int, int, int]:
    """
    Verify dataset exists and count images.

    Returns:
        Tuple of (train_count, val_count, test_count)
    """
    train_flood = len(list((FLOOD_IMAGES_DIR / "train" / "flood").glob("*.jpg")))
    train_no_flood = len(list((FLOOD_IMAGES_DIR / "train" / "no_flood").glob("*.jpg")))
    val_flood = len(list((FLOOD_IMAGES_DIR / "val" / "flood").glob("*.jpg")))
    val_no_flood = len(list((FLOOD_IMAGES_DIR / "val" / "no_flood").glob("*.jpg")))
    test_flood = len(list((FLOOD_IMAGES_DIR / "test" / "flood").glob("*.jpg")))
    test_no_flood = len(list((FLOOD_IMAGES_DIR / "test" / "no_flood").glob("*.jpg")))

    train_count = train_flood + train_no_flood
    val_count = val_flood + val_no_flood
    test_count = test_flood + test_no_flood

    logger.info(f"Dataset summary:")
    logger.info(f"  Train: {train_count} ({train_flood} flood, {train_no_flood} no_flood)")
    logger.info(f"  Val:   {val_count} ({val_flood} flood, {val_no_flood} no_flood)")
    logger.info(f"  Test:  {test_count} ({test_flood} flood, {test_no_flood} no_flood)")

    return train_count, val_count, test_count


def create_dataset_yaml() -> Path:
    """
    Create dataset.yaml for YOLOv8 classification.

    Returns:
        Path to created YAML file
    """
    yaml_content = f"""# YOLOv8 Flood Classification Dataset
# Auto-generated by train_flood_classifier.py
# Created: {datetime.now().isoformat()}

path: {FLOOD_IMAGES_DIR.absolute()}
train: train
val: val
test: test

# Class names (0 = no_flood, 1 = flood)
names:
  0: no_flood
  1: flood

# CRITICAL SAFETY NOTE:
# We use low threshold (0.3) during inference to minimize false negatives
# Target: <2% False Negative Rate
"""

    yaml_path = FLOOD_IMAGES_DIR / "dataset.yaml"
    yaml_path.write_text(yaml_content)
    logger.info(f"Created dataset.yaml at {yaml_path}")
    return yaml_path


def evaluate_model(model, test_dir: Path) -> Dict[str, Any]:
    """
    Evaluate trained model on test set.

    Calculates:
    - Accuracy
    - Precision
    - Recall (CRITICAL: must be >98%)
    - False Negative Rate (CRITICAL: must be <2%)
    - F1 Score

    Args:
        model: Trained YOLO model
        test_dir: Path to test directory

    Returns:
        Evaluation metrics dictionary
    """
    from PIL import Image

    flood_dir = test_dir / "flood"
    no_flood_dir = test_dir / "no_flood"

    # Test flood images
    tp = 0  # True Positives (flood correctly identified)
    fn = 0  # False Negatives (flood missed - CRITICAL)

    for img_path in flood_dir.glob("*.jpg"):
        try:
            results = model(str(img_path), verbose=False)
            probs = results[0].probs

            if probs is not None:
                # YOLOv8 uses alphabetical class ordering: flood=0, no_flood=1
                flood_prob = float(probs.data[0])
                # Using low threshold for safety
                if flood_prob >= 0.3:
                    tp += 1
                else:
                    fn += 1
                    logger.warning(f"MISSED FLOOD: {img_path.name} (prob: {flood_prob:.3f})")
        except Exception as e:
            logger.error(f"Failed to evaluate {img_path}: {e}")
            fn += 1

    # Test non-flood images
    tn = 0  # True Negatives (no_flood correctly identified)
    fp = 0  # False Positives (no_flood marked as flood)

    for img_path in no_flood_dir.glob("*.jpg"):
        try:
            results = model(str(img_path), verbose=False)
            probs = results[0].probs

            if probs is not None:
                # YOLOv8 uses alphabetical class ordering: flood=0, no_flood=1
                flood_prob = float(probs.data[0])
                if flood_prob < 0.3:
                    tn += 1
                else:
                    fp += 1
        except Exception as e:
            logger.error(f"Failed to evaluate {img_path}: {e}")
            tn += 1

    # Calculate metrics
    total = tp + tn + fp + fn
    accuracy = (tp + tn) / total if total > 0 else 0
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0  # CRITICAL metric
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0
    fnr = fn / (tp + fn) if (tp + fn) > 0 else 0  # CRITICAL: must be <2%
    fpr = fp / (tn + fp) if (tn + fp) > 0 else 0

    metrics = {
        "total_images": total,
        "true_positives": tp,
        "true_negatives": tn,
        "false_positives": fp,
        "false_negatives": fn,
        "accuracy": round(accuracy, 4),
        "precision": round(precision, 4),
        "recall": round(recall, 4),
        "f1_score": round(f1, 4),
        "false_negative_rate": round(fnr, 4),
        "false_positive_rate": round(fpr, 4),
        "safety_passed": fnr < 0.02,  # <2% FNR requirement
    }

    return metrics


def save_training_results(
    metrics: Dict[str, Any],
    output_dir: Path,
    model_path: Path
) -> Path:
    """
    Save training results and metrics to JSON.

    Args:
        metrics: Evaluation metrics
        output_dir: Output directory
        model_path: Path to trained model

    Returns:
        Path to results JSON file
    """
    results = {
        "timestamp": datetime.now().isoformat(),
        "model_path": str(model_path),
        "metrics": metrics,
        "safety_config": {
            "flood_threshold": 0.3,
            "target_fnr": 0.02,
            "target_recall": 0.98,
        }
    }

    results_path = output_dir / "training_results.json"
    with open(results_path, 'w') as f:
        json.dump(results, f, indent=2)

    logger.info(f"Saved training results to {results_path}")
    return results_path


def train(
    epochs: int = DEFAULT_EPOCHS,
    batch: int = DEFAULT_BATCH,
    imgsz: int = DEFAULT_IMGSZ,
    resume: bool = False
) -> Dict[str, Any]:
    """
    Train the flood classifier.

    Args:
        epochs: Number of training epochs
        batch: Batch size
        imgsz: Image size
        resume: Resume from last checkpoint

    Returns:
        Training results and metrics
    """
    try:
        from ultralytics import YOLO
    except ImportError:
        logger.error("ultralytics not installed. Run: pip install ultralytics")
        return {"error": "ultralytics not installed"}

    # Check dataset
    train_count, val_count, test_count = check_dataset()

    if train_count == 0:
        logger.error("No training images found. Run the data collection scripts first.")
        logger.error("  1. python -m apps.ml-service.scripts.download_kaggle_datasets")
        logger.error("  2. python -m apps.ml-service.scripts.scrape_flood_images")
        logger.error("  3. python -m apps.ml-service.scripts.preprocess_flood_images")
        return {"error": "No training data"}

    # Create dataset YAML
    yaml_path = create_dataset_yaml()

    # Create output directory
    output_dir = MODELS_DIR / "yolov8_flood"
    output_dir.mkdir(parents=True, exist_ok=True)

    # Initialize model
    if resume:
        last_checkpoint = output_dir / "runs" / "classify" / "flood_classifier" / "weights" / "last.pt"
        if last_checkpoint.exists():
            logger.info(f"Resuming from {last_checkpoint}")
            model = YOLO(str(last_checkpoint))
        else:
            logger.warning("No checkpoint found, starting fresh")
            model = YOLO("yolov8n-cls.pt")
    else:
        logger.info("Initializing YOLOv8n-cls from pretrained weights")
        model = YOLO("yolov8n-cls.pt")

    # Train
    logger.info(f"\nStarting training for {epochs} epochs...")
    logger.info(f"Batch size: {batch}, Image size: {imgsz}")

    # For YOLOv8 classification, pass directory path, not YAML
    # Directory structure: flood_images/{train,val,test}/{flood,no_flood}/
    results = model.train(
        data=str(FLOOD_IMAGES_DIR),
        epochs=epochs,
        imgsz=imgsz,
        batch=batch,
        # Project settings
        project=str(output_dir / "runs" / "classify"),
        name="flood_classifier",
        exist_ok=True,
        # Optimizer
        optimizer="AdamW",
        lr0=0.001,
        lrf=0.01,
        weight_decay=0.0005,
        # Training
        patience=20,
        save=True,
        save_period=10,
        # Augmentation for robustness
        augment=True,
        hsv_h=0.015,
        hsv_s=0.7,
        hsv_v=0.4,
        degrees=10.0,
        translate=0.1,
        scale=0.5,
        flipud=0.5,
        fliplr=0.5,
        mosaic=0.5,
        mixup=0.1,
        # Logging
        verbose=True,
        plots=True,
        # Memory optimization - fewer workers reduces pin_memory overhead
        workers=2,
    )

    # Get best model path
    best_model_path = output_dir / "runs" / "classify" / "flood_classifier" / "weights" / "best.pt"

    if not best_model_path.exists():
        logger.error("Training failed - no best.pt found")
        return {"error": "Training failed"}

    # Evaluate on test set
    logger.info("\nEvaluating model on test set...")
    test_dir = FLOOD_IMAGES_DIR / "test"
    metrics = evaluate_model(model, test_dir)

    # Print evaluation results
    print("\n" + "="*60)
    print("EVALUATION RESULTS")
    print("="*60)
    print(f"Total test images: {metrics['total_images']}")
    print(f"Accuracy: {metrics['accuracy']*100:.2f}%")
    print(f"Precision: {metrics['precision']*100:.2f}%")
    print(f"Recall: {metrics['recall']*100:.2f}%")
    print(f"F1 Score: {metrics['f1_score']*100:.2f}%")
    print(f"\n{'─'*60}")
    print(f"FALSE NEGATIVE RATE: {metrics['false_negative_rate']*100:.2f}%")
    print(f"Target: <2%")
    print(f"{'─'*60}")

    if metrics['safety_passed']:
        print(f"\n✅ SAFETY PASSED: FNR {metrics['false_negative_rate']*100:.2f}% < 2%")
    else:
        print(f"\n❌ SAFETY FAILED: FNR {metrics['false_negative_rate']*100:.2f}% >= 2%")
        print("   Model needs improvement before deployment!")

    print("="*60 + "\n")

    # Copy best model to standard location
    final_model_path = output_dir / "flood_classifier_v1.pt"
    shutil.copy(best_model_path, final_model_path)
    logger.info(f"Best model saved to {final_model_path}")

    # Save results
    save_training_results(metrics, output_dir, final_model_path)

    return {
        "model_path": str(final_model_path),
        "metrics": metrics,
        "training_complete": True
    }


def main():
    parser = argparse.ArgumentParser(description="Train YOLOv8 flood classifier")
    parser.add_argument(
        "--epochs",
        type=int,
        default=DEFAULT_EPOCHS,
        help=f"Training epochs (default: {DEFAULT_EPOCHS})"
    )
    parser.add_argument(
        "--batch",
        type=int,
        default=DEFAULT_BATCH,
        help=f"Batch size (default: {DEFAULT_BATCH})"
    )
    parser.add_argument(
        "--imgsz",
        type=int,
        default=DEFAULT_IMGSZ,
        help=f"Image size (default: {DEFAULT_IMGSZ})"
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Resume from last checkpoint"
    )

    args = parser.parse_args()

    print("\n" + "="*60)
    print("FLOOD CLASSIFIER TRAINING")
    print("="*60)
    print(f"Epochs: {args.epochs}")
    print(f"Batch: {args.batch}")
    print(f"Image size: {args.imgsz}")
    print(f"Resume: {args.resume}")
    print("\nSAFETY TARGET: <2% False Negative Rate")
    print("="*60 + "\n")

    results = train(
        epochs=args.epochs,
        batch=args.batch,
        imgsz=args.imgsz,
        resume=args.resume
    )

    if "error" in results:
        logger.error(f"Training failed: {results['error']}")
        return 1

    if not results["metrics"]["safety_passed"]:
        logger.warning("Model did not pass safety requirements")
        logger.warning("Consider: more training data, more epochs, or threshold adjustment")
        return 2

    logger.info("Training completed successfully!")
    return 0


if __name__ == "__main__":
    sys.exit(main())
